add_library(fhe_layers
  layer.cpp
  layer_util.cpp
  conv2d_layer.cpp
  upsample_layer.cpp
  upsample_nearest_layer.cpp
  inverse_multiplexed_conv2d_layer.cpp
  inverse_multiplexed_conv2d_layer_depthwise.cpp
  concat_layer.cpp
  conv2d_packed_layer.cpp 
  activation_layer.cpp 
  complex_btp_layer.cpp
  complex_pack_layer.cpp
  complex_unpack_layer.cpp
  dense_packed_layer.cpp
  reshape_layer.cpp
  add_layer.cpp
  conv2d_depthwise.cpp
  avgpool2d_layer.cpp
  avgpool1d_layer.cpp
  multiplexed_conv2d_pack_layer.cpp
  multiplexed_conv2d_pack_layer_depthwise.cpp
  poly_relu2d.cpp
  poly_relu1d.cpp
  poly_relu_base.cpp
  mat_poly_base.cpp
  mult_scaler.cpp
  conv1d_packed_layer.cpp
  multiplexed_conv1d_pack_layer.cpp
  multiplexed_conv1d_depthwise_pack_layer.cpp
  par_block_col_major_transpose.cpp
  par_block_col_major_ccmm.cpp
  par_block_col_major_cpmm.cpp
  par_lower_diag_pcmm.cpp
  par_lower_diag_ccmm.cpp
  par_lower_diag_transpose.cpp
  par_block_col_major_add_pt.cpp
  par_lower_diagonal_add_pt.cpp
  block_col_major_layernorm.cpp
  par_block_col_major_layernorm.cpp
  par_upper_diagonal_layernorm.cpp
  block_col_major_polyactrn.cpp
  par_block_col_major_polyactrn.cpp
  par_upper_diagonal_polyact.cpp
  par_upper_diagonal_poly_mult_ct.cpp
  par_upper_diagonal_poly.cpp
  par_upper_diagonal_softmax.cpp
  ../data_structs/feature.cpp
  ../data_structs/feature1d.cpp
  ../data_structs/feature2d.cpp
  ../data_structs/feature_mat.cpp
  ../data_structs/feature0d.cpp
  ../util.cpp
)
target_include_directories(fhe_layers PUBLIC 
  ${CMAKE_SOURCE_DIR}/data_structs/
)
find_package(OpenMP)
if(OpenMP_CXX_FOUND)
  target_link_libraries(fhe_layers PUBLIC lattisense OpenMP::OpenMP_CXX)
else()
  target_link_libraries(fhe_layers PUBLIC lattisense)
endif()

target_precompile_headers(fhe_layers PRIVATE
  <nlohmann/json.hpp>
  <cxx_sdk_v2/cxx_fhe_task.h>
)
