/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Example: Encrypted inference on MNIST using CKKS scheme.
//
// This demo loads a pre-trained MNIST model and runs inference on a single
// encrypted image (1x16x16).  It then compares the ciphertext result against
// a plaintext reference to verify correctness.

#include <cstring>
#include <iostream>
#include <map>
#include <memory>
#include <vector>

#include <cxx_sdk_v2/cxx_fhe_task.h>
#include "data_structs/feature.h"
#include "inference_task/inference_process.h"
#include "util.h"

using namespace cxx_sdk_v2;
using namespace std;

int main(int argc, char* argv[]) {
    bool use_gpu = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--gpu") == 0)
            use_gpu = true;
    }

    cout << "========== MNIST Encrypted Inference ==========" << endl;
    cout << "Device: " << (use_gpu ? "GPU" : "CPU") << endl;

    // ==================== 1. Read Configuration ====================
    // Load client-side task config and CKKS parameters from JSON files.
    // These configs are generated by the model compilation step.
    auto task_config = read_json("./task/client/task_config.json");
    auto& input_param = task_config["task_input_param"].begin().value();
    auto& output_param = task_config["task_output_param"].begin().value();
    // Ciphertext multiplication depth level for the input
    int level = input_param["level"];
    // Stride between valid data slots in the output ciphertext
    int output_skip = output_param["skip"];
    int channel = input_param["channel"];
    int height = input_param["shape"][0];
    int width = input_param["shape"][1];
    // Packing style: "ordinary" (one channel per ciphertext) or
    // "multiplexed": (generalized interleaved packing strategy)
    string pack_style = task_config["pack_style"];

    auto ckks_config = read_json("./task/client/ckks_parameter.json");
    string ckks_param_id = input_param["ckks_parameter_id"];
    // Number of usable CKKS slots = poly_modulus_degree / 2
    int n_slots = ckks_config[ckks_param_id]["poly_modulus_degree"].get<int>() / 2;

    // ==================== 2. Client Side: Encrypt Input ====================
    // Read the input image from CSV file with shape [channel, height, width].
    auto input_array = csv_to_array<3>("./task/client/img.csv", {(uint64_t)channel, (uint64_t)height, (uint64_t)width});

    // Create CKKS encryption context (without bootstrapping for MNIST).
    cout << "[Context] Generating CKKS context and keys..." << endl;
    CkksParameter param = CkksParameter::create_parameter(16384);
    CkksContext context = CkksContext::create_random_context(param);
    // Generate rotation public keys (for SIMD rotation operations on ciphertext vectors)
    context.gen_rotation_keys();
    cout << "[Context] Done." << endl;

    // Create an encrypted feature map and pack the input data.
    // The packing strategy depends on the image size relative to the
    // number of available CKKS slots:
    //   - ordinary:     one channel per ciphertext (simple packing)
    //   - multiplexed:  generalized interleaved packing
    //       - if image pixels > n_slots: split into blocks first
    //       - otherwise: parallel multiplexed packing
    cout << "[Encrypt] Encrypting input..." << endl;
    Feature2DEncrypted input_ct(&context, level);

    if (pack_style == "ordinary") {
        input_ct.pack(input_array, false, param.get_default_scale());
    } else if (height * width > n_slots) {
        // Image too large for a single ciphertext: split into blocks and
        // pack each block separately.  channel_packing_factor indicates
        // how many blocks tile each spatial dimension.
        Duo block_shape = {task_config["block_shape"][0], task_config["block_shape"][1]};
        Duo channel_packing_factor = {(uint32_t)(height / block_shape[0]), (uint32_t)(width / block_shape[1])};
        input_ct.split_with_stride_pack(input_array, block_shape, channel_packing_factor, false,
                                        param.get_default_scale());
    } else {
        // Image fits in one ciphertext: use parallel multiplexed packing
        // to encode multiple channels into a single ciphertext.
        input_ct.par_mult_pack(input_array, false, param.get_default_scale());
    }
    cout << "[Encrypt] Done." << endl;

    // ==================== 3. Server Side: Load Model ====================
    // Load the pre-compiled encrypted computation graph and model weights.
    // No bootstrapping parameters needed for MNIST (smaller model depth).
    InitInferenceProcess init("./task/server/", false);
    init.init_parameters();
    init.is_lazy = false;
    init.load_model_prepare();

    // ==================== 4. Run Encrypted Inference ====================
    // Configure the inference engine with the encryption context and
    // encrypted input, then execute the computation graph.
    InferenceProcess fp(&init, true);
    fp.available_keys.push_back("input");

    // Pass the encryption context to the server-side inference engine.
    map<string, unique_ptr<CkksContext>> context_map;
    context_map["param0"] = make_unique<CkksContext>(move(context.shallow_copy_context()));
    fp.ckks_contexts = move(context_map);
    fp.set_feature("input", make_unique<Feature2DEncrypted>(move(input_ct)));

    // Select compute device: multi-threaded CPU or GPU hardware acceleration
    fp.compute_device = use_gpu ? ComputeDevice::GPU : ComputeDevice::CPU;
    // Execute the full FHE ciphertext inference pipeline
    cout << "[Inference] Running encrypted inference..." << endl;
    Timer timer;
    timer.start();
    fp.run_task();
    timer.stop();
    timer.print("Encrypted inference time");
    cout << "[Inference] Done." << endl;

    // ==================== 5. Decrypt and Verify ====================
    // Retrieve the encrypted output and decrypt it.
    // output_skip specifies the stride between valid classification scores
    // in the packed ciphertext slots.
    auto encrypted_output = fp.get_ciphertext_output_feature0D("output");
    encrypted_output.skip = output_skip;
    auto decrypted = encrypted_output.unpack(DecryptType::SPARSE);
    print_double_message(decrypted.to_array_1d().data(), "Encrypted output", 10);

    // Run plaintext inference on the same input as a correctness reference.
    fp.p_feature2d_x["input"] = std::move(input_array);
    fp.run_task_plaintext();
    auto plain_output = fp.p_feature0d_x["output"];
    print_double_message(plain_output.data(), "Plaintext output", 10);

    return 0;
}
