/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Multi-layer end-to-end inference tests.
//
// Test data is generated by running test_compiler.py::TestE2EMultipleLayer which
// produces complete task directories under build/inference/hetero_e2e/multiple_layer/<test_name>/.
//
// Single-layer tests live in test_e2e_single_layer.cpp (generated by TestE2ESingleLayer).
//
// Usage:
//   ./test_e2e_multiple_layer "[e2e]"                # Run all working tests
//   ./test_e2e_multiple_layer "[cpu]"                # Run all working CPU tests
//   ./test_e2e_multiple_layer "[gpu]"                # Run all working GPU tests
//   ./test_e2e_multiple_layer "cpu/conv_act"         # Run a specific CPU test
//   ./test_e2e_multiple_layer "gpu/conv_act"         # Run a specific GPU test
//   ./test_e2e_multiple_layer "cpu/all"              # Run all CPU tests (batch)
//   ./test_e2e_multiple_layer "gpu/all"              # Run all GPU tests (batch)

#define CATCH_CONFIG_MAIN
#include "e2e_test_util.h"

static const fs::path multiple_layer_base_path = e2e_base_path / "multiple_layer";

// clang-format off
static const std::vector<std::string> all_test_names = {
    "conv_batchnorm", "concat_e2e", "uneven_concat",
    "poly_n_8192", "conv_act", "resnet_basic_block", "poly_n_32768",
    "act_series",
    "mux_conv_large_channel",
    "conv_avgpool_reshape_dense", "avgpool_stride4",
    "general_avgpool",
    "conv_reshape_dense",
    "two_fc",
    "conv1d_reshape_dense",
};
// clang-format on

TEST_CASE("cpu/all", "[batch][cpu]") {
    for (const auto& name : all_test_names) {
        SECTION(name) {
            run_e2e_test(multiple_layer_base_path / name, false);
        }
    }
}

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/all", "[batch][gpu]") {
    for (const auto& name : all_test_names) {
        SECTION(name) {
            run_e2e_test(multiple_layer_base_path / name, true);
        }
    }
}
#endif

// == CPU tests ================================================================

TEST_CASE("cpu/conv_batchnorm", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_batchnorm", false);
}
TEST_CASE("cpu/concat_e2e", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "concat_e2e", false);
}
TEST_CASE("cpu/uneven_concat", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "uneven_concat", false);
}
TEST_CASE("cpu/poly_n_8192", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "poly_n_8192", false);
}
TEST_CASE("cpu/conv_act", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_act", false);
}
TEST_CASE("cpu/resnet_basic_block", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "resnet_basic_block", false);
}
TEST_CASE("cpu/poly_n_32768", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "poly_n_32768", false);
}
TEST_CASE("cpu/act_series", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "act_series", false);
}
TEST_CASE("cpu/mux_conv_large_channel", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "mux_conv_large_channel", false);
}
TEST_CASE("cpu/conv_avgpool_reshape_dense", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_avgpool_reshape_dense", false);
}
TEST_CASE("cpu/avgpool_stride4", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "avgpool_stride4", false);
}
TEST_CASE("cpu/general_avgpool", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "general_avgpool", false);
}
TEST_CASE("cpu/conv_reshape_dense", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_reshape_dense", false);
}
TEST_CASE("cpu/two_fc", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "two_fc", false);
}
TEST_CASE("cpu/conv1d_reshape_dense", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv1d_reshape_dense", false);
}
TEST_CASE("cpu/conv_upsample_e2e", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_upsample_e2e", false);
}
TEST_CASE("cpu/multiple_inputs", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "multiple_inputs", false);
}
TEST_CASE("cpu/multiple_outputs", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "multiple_outputs", false);
}
TEST_CASE("cpu/conv_concat_conv", "[e2e][cpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_concat_conv", false);
}

// == GPU tests ================================================================

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/conv_batchnorm", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_batchnorm", true);
}
TEST_CASE("gpu/concat_e2e", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "concat_e2e", true);
}
TEST_CASE("gpu/uneven_concat", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "uneven_concat", true);
}
TEST_CASE("gpu/poly_n_8192", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "poly_n_8192", true);
}
TEST_CASE("gpu/conv_act", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_act", true);
}
TEST_CASE("gpu/resnet_basic_block", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "resnet_basic_block", true);
}
TEST_CASE("gpu/poly_n_32768", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "poly_n_32768", true);
}
TEST_CASE("gpu/act_series", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "act_series", true);
}
TEST_CASE("gpu/mux_conv_large_channel", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "mux_conv_large_channel", true);
}
TEST_CASE("gpu/conv_reshape_dense", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_reshape_dense", true);
}
TEST_CASE("gpu/two_fc", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "two_fc", true);
}
TEST_CASE("gpu/conv1d_reshape_dense", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv1d_reshape_dense", true);
}
TEST_CASE("gpu/conv_avgpool_reshape_dense", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_avgpool_reshape_dense", true);
}
TEST_CASE("gpu/avgpool_stride4", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "avgpool_stride4", true);
}
TEST_CASE("gpu/general_avgpool", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "general_avgpool", true);
}
TEST_CASE("gpu/conv_upsample_e2e", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_upsample_e2e", true);
}
TEST_CASE("gpu/multiple_inputs", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "multiple_inputs", true);
}
TEST_CASE("gpu/multiple_outputs", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "multiple_outputs", true);
}
TEST_CASE("gpu/conv_concat_conv", "[e2e][gpu]") {
    run_e2e_test(multiple_layer_base_path / "conv_concat_conv", true);
}
#endif

// == Known broken tests (disabled) ============================================
// These tests crash (GPU OOM, Go panic, C++ abort) and are disabled until fixed.
// See docs/e2e_test_status.md for details.
//
// Both CPU and GPU:
//   poly_n_65536_no_btp, btp, conv_series, intertwined
