/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// End-to-end inference test: verifies that encrypted inference produces results
// consistent with plaintext inference using the InferenceClient/InferenceServer API.
//
// Test data is generated by running test_compiler.py::TestE2E which produces
// complete task directories under build/inference/hetero_e2e/<test_name>/.
//
// Usage:
//   ./test_e2e "[cpu]"              # Run all CPU tests
//   ./test_e2e "[gpu]"              # Run all GPU tests
//   ./test_e2e "[e2e]"              # Run all (CPU + GPU)
//   ./test_e2e "e2e_cpu/conv_act"   # Run a specific CPU test

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <cmath>
#include <filesystem>
#include <map>
#include <string>
#include <vector>

#include "interface/inference_client.h"
#include "interface/inference_server.h"
#include "util.h"

using namespace std;
namespace fs = std::filesystem;

static const fs::path e2e_base_path = "../hetero_e2e";

static vector<fs::path> discover_tests(const fs::path& base) {
    vector<fs::path> result;
    if (!fs::exists(base))
        return result;
    for (auto& entry : fs::directory_iterator(base)) {
        if (!entry.is_directory())
            continue;
        auto client_config = entry.path() / "task" / "client" / "task_config.json";
        auto server_config = entry.path() / "task" / "server" / "task_config.json";
        if (fs::exists(client_config) && fs::exists(server_config)) {
            result.push_back(entry.path());
        }
    }
    sort(result.begin(), result.end());
    return result;
}

static void run_e2e_test(const fs::path& test_dir, bool use_gpu) {
    string test_name = test_dir.filename().string();
    string client_dir = (test_dir / "task" / "client").string();
    string server_dir = (test_dir / "task" / "server").string();

    // Read task_config to get input names and build CSV map
    auto task_config = read_json(client_dir + "/task_config.json");
    map<string, string> input_csvs;
    for (auto& [name, param] : task_config["task_input_param"].items()) {
        string csv_path = client_dir + "/" + name + ".csv";
        REQUIRE(fs::exists(csv_path));
        input_csvs[name] = csv_path;
    }

    // Client: generate keys and encrypt input
    InferenceClient client(client_dir);
    client.setup();
    auto eval_ctx = client.export_eval_context();
    auto encrypted_inputs = client.encrypt(input_csvs);

    // Server: import context, load model, run encrypted inference
    InferenceServer server(server_dir, use_gpu);
    server.import_eval_context(eval_ctx);
    server.load_model();
    auto encrypted_outputs = server.evaluate(encrypted_inputs);

    // Client: decrypt results
    auto results = client.decrypt(encrypted_outputs);

    // Server: run plaintext reference inference
    auto plaintext_outputs = server.evaluate_plaintext(input_csvs);

    // Compare encrypted vs plaintext outputs
    constexpr double tolerance = 0.1;
    for (auto& [name, result] : results) {
        auto pt_it = plaintext_outputs.find(name);
        REQUIRE(pt_it != plaintext_outputs.end());
        auto& pt_output = pt_it->second;

        int count = min(result.num_outputs, (int)pt_output.size());
        REQUIRE(count > 0);

        double max_abs_err = 0.0;
        int max_err_idx = 0;
        for (int i = 0; i < count; i++) {
            double abs_err = fabs(result.output[i] - pt_output[i]);
            if (abs_err > max_abs_err) {
                max_abs_err = abs_err;
                max_err_idx = i;
            }
        }

        INFO("Test: " << test_name << " (" << (use_gpu ? "GPU" : "CPU") << "), Output: " << name
                      << ", Max error: " << max_abs_err << " at index " << max_err_idx);
        REQUIRE(max_abs_err < tolerance);
    }
}

TEST_CASE("e2e_cpu", "[e2e][cpu]") {
    auto test_dirs = discover_tests(e2e_base_path);
    REQUIRE_FALSE(test_dirs.empty());

    for (const auto& test_dir : test_dirs) {
        SECTION(test_dir.filename().string()) {
            run_e2e_test(test_dir, false);
        }
    }
}

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("e2e_gpu", "[e2e][gpu]") {
    auto test_dirs = discover_tests(e2e_base_path);
    REQUIRE_FALSE(test_dirs.empty());

    for (const auto& test_dir : test_dirs) {
        SECTION(test_dir.filename().string()) {
            run_e2e_test(test_dir, true);
        }
    }
}
#endif
