/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// End-to-end inference test: verifies that encrypted inference produces results
// consistent with plaintext inference using the InferenceClient/InferenceServer API.
//
// Test data is generated by running test_compiler.py::TestE2E which produces
// complete task directories under build/inference/hetero_e2e/<test_name>/.
//
// Usage:
//   ./test_e2e "[e2e]"                # Run all working tests
//   ./test_e2e "[cpu]"                # Run all working CPU tests
//   ./test_e2e "[gpu]"                # Run all working GPU tests
//   ./test_e2e "cpu/single_conv"      # Run a specific CPU test
//   ./test_e2e "gpu/single_conv"      # Run a specific GPU test
//   ./test_e2e "cpu/all"              # Run all CPU tests (batch)
//   ./test_e2e "gpu/all"              # Run all GPU tests (batch)

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <chrono>
#include <cmath>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "interface/inference_client.h"
#include "interface/inference_server.h"
#include "util.h"

using namespace std;
namespace fs = std::filesystem;

static const fs::path e2e_base_path = "../hetero_e2e";

static void run_e2e_test(const fs::path& test_dir, bool use_gpu) {
    using clock = chrono::high_resolution_clock;
    string test_name = test_dir.filename().string();
    string device_tag = use_gpu ? "GPU" : "CPU";
    fs::path client_dir = test_dir / "task" / "client";
    fs::path server_dir = test_dir / "task" / "server";

    // Read task_config to get input names and build CSV map
    auto task_config = read_json((client_dir / "task_config.json").string());
    map<string, string> input_csvs;
    for (auto& [name, param] : task_config["task_input_param"].items()) {
        fs::path csv_path = client_dir / (name + ".csv");
        REQUIRE(fs::exists(csv_path));
        input_csvs[name] = csv_path.string();
    }

    // Timing records: label -> duration in ms
    struct TimingRecord {
        const char* label;
        double ms;
    };
    vector<TimingRecord> timings;
    auto measure = [&](const char* label, auto&& fn) {
        auto t0 = clock::now();
        auto result = fn();
        auto t1 = clock::now();
        timings.push_back({label, chrono::duration<double, milli>(t1 - t0).count()});
        return result;
    };
    auto measure_void = [&](const char* label, auto&& fn) {
        auto t0 = clock::now();
        fn();
        auto t1 = clock::now();
        timings.push_back({label, chrono::duration<double, milli>(t1 - t0).count()});
    };

    // Client: generate keys and encrypt input
    InferenceClient client(client_dir.string());
    measure_void("Key generation", [&] { client.setup(); });
    auto eval_ctx = measure("Export eval context", [&] { return client.export_eval_context(); });
    auto encrypted_inputs = measure("Encrypt input", [&] { return client.encrypt(input_csvs); });

    // Server: import context, load model, run encrypted inference
    InferenceServer server(server_dir.string(), use_gpu);
    measure_void("Import eval context", [&] { server.import_eval_context(eval_ctx); });
    measure_void("Load model", [&] { server.load_model(); });
    auto encrypted_outputs = measure("Evaluate (encrypted)", [&] { return server.evaluate(encrypted_inputs); });

    // Client: decrypt results
    auto results = measure("Decrypt output", [&] { return client.decrypt(encrypted_outputs); });

    // Server: run plaintext reference inference
    auto plaintext_outputs = measure("Evaluate (plaintext)", [&] { return server.evaluate_plaintext(input_csvs); });

    // Print timing summary
    double total_ms = 0.0;
    for (auto& t : timings)
        total_ms += t.ms;
    cout << "\n[" << test_name << "] (" << device_tag << ") Timing:" << endl;
    for (auto& t : timings) {
        cout << "  " << left << setw(24) << t.label << right << setw(10) << fixed << setprecision(2) << t.ms << " ms"
             << endl;
    }
    cout << "  " << string(34, '-') << endl;
    cout << "  " << left << setw(24) << "Total" << right << setw(10) << fixed << setprecision(2) << total_ms << " ms"
         << endl;

    // Compare encrypted vs plaintext outputs
    constexpr double tolerance = 0.1;
    for (auto& [name, result] : results) {
        auto pt_it = plaintext_outputs.find(name);
        REQUIRE(pt_it != plaintext_outputs.end());
        auto& pt_output = pt_it->second;

        int count = min(result.num_outputs, static_cast<int>(pt_output.size()));
        REQUIRE(count > 0);

        double max_abs_err = 0.0;
        int max_err_idx = 0;
        for (int i = 0; i < count; i++) {
            double abs_err = fabs(result.output[i] - pt_output[i]);
            if (abs_err > max_abs_err) {
                max_abs_err = abs_err;
                max_err_idx = i;
            }
        }

        // Print first 10 plaintext/ciphertext values for manual comparison
        int preview_count = min(count, 10);
        cout << defaultfloat << setprecision(4);
        cout << "[" << test_name << "] Output: " << name << " (" << device_tag << ", " << count << " values)" << endl;
        cout << "  Plaintext : ";
        for (int i = 0; i < preview_count; i++) {
            cout << pt_output[i] << (i < preview_count - 1 ? ", " : "");
        }
        cout << endl;
        cout << "  Ciphertext: ";
        for (int i = 0; i < preview_count; i++) {
            cout << result.output[i] << (i < preview_count - 1 ? ", " : "");
        }
        cout << endl;
        cout << "  Max error : " << scientific << max_abs_err << " at index " << max_err_idx << endl;

        INFO("Test: " << test_name << " (" << device_tag << "), Output: " << name << ", Max error: " << max_abs_err
                      << " at index " << max_err_idx);
        REQUIRE(max_abs_err < tolerance);
    }
}

// == Run all (batch) ==========================================================

// clang-format off
static const vector<string> all_test_names = {
    "single_conv", "single_act", "single_dense",
    "conv_batchnorm", "concat_e2e", "uneven_concat",
    "poly_n_8192", "conv_act", "resnet_basic_block", "poly_n_32768",
    "act_series",
    "conv_mch_s1", "conv_mch_s2",
    "depthwise_conv_s1", "depthwise_conv_s2",
    "mux_conv_large_channel",
    "single_avgpool", 
    "conv_avgpool_reshape_dense", "avgpool_stride4",
    "general_avgpool",
    "conv_reshape_dense",
    "two_fc",
    "conv1d_e2e",
};
// clang-format on

TEST_CASE("cpu/all", "[batch][cpu]") {
    for (const auto& name : all_test_names) {
        SECTION(name) {
            run_e2e_test(e2e_base_path / name, false);
        }
    }
}

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/all", "[batch][gpu]") {
    for (const auto& name : all_test_names) {
        SECTION(name) {
            run_e2e_test(e2e_base_path / name, true);
        }
    }
}
#endif

// == CPU tests ================================================================

TEST_CASE("cpu/single_conv", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_conv", false);
}
TEST_CASE("cpu/single_act", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_act", false);
}
TEST_CASE("cpu/single_dense", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_dense", false);
}
TEST_CASE("cpu/conv_batchnorm", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_batchnorm", false);
}
TEST_CASE("cpu/concat_e2e", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "concat_e2e", false);
}
TEST_CASE("cpu/uneven_concat", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "uneven_concat", false);
}
TEST_CASE("cpu/poly_n_8192", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "poly_n_8192", false);
}
TEST_CASE("cpu/conv_act", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_act", false);
}
TEST_CASE("cpu/resnet_basic_block", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "resnet_basic_block", false);
}
TEST_CASE("cpu/poly_n_32768", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "poly_n_32768", false);
}
TEST_CASE("cpu/act_series", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "act_series", false);
}
TEST_CASE("cpu/conv_mch_s1", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_mch_s1", false);
}
TEST_CASE("cpu/conv_mch_s2", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_mch_s2", false);
}
TEST_CASE("cpu/depthwise_conv_s1", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "depthwise_conv_s1", false);
}
TEST_CASE("cpu/depthwise_conv_s2", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "depthwise_conv_s2", false);
}
TEST_CASE("cpu/mux_conv_large_channel", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "mux_conv_large_channel", false);
}
TEST_CASE("cpu/single_avgpool", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_avgpool", false);
}
TEST_CASE("cpu/conv_avgpool_reshape_dense", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_avgpool_reshape_dense", false);
}
TEST_CASE("cpu/avgpool_stride4", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "avgpool_stride4", false);
}
TEST_CASE("cpu/general_avgpool", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "general_avgpool", false);
}
TEST_CASE("cpu/conv_reshape_dense", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_reshape_dense", false);
}
TEST_CASE("cpu/two_fc", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "two_fc", false);
}
TEST_CASE("cpu/conv1d_e2e", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv1d_e2e", false);
}

TEST_CASE("cpu/single_avgpool_big_size", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_avgpool_big_size", false);
}
TEST_CASE("cpu/single_conv_with_stride_big_size", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_conv_with_stride_big_size", false);
}
TEST_CASE("cpu/dw_conv_big_size", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "dw_conv_big_size", false);
}
TEST_CASE("cpu/single_add", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "single_add", false);
}
TEST_CASE("cpu/conv_upsample_e2e", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_upsample_e2e", false);
}

TEST_CASE("cpu/multiple_inputs", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "multiple_inputs", false);
}

TEST_CASE("cpu/multiple_outputs", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "multiple_outputs", false);
}
TEST_CASE("cpu/conv_concat_conv", "[e2e][cpu]") {
    run_e2e_test(e2e_base_path / "conv_concat_conv", false);
}
// == GPU tests ================================================================

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/single_conv", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_conv", true);
}
TEST_CASE("gpu/single_act", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_act", true);
}
TEST_CASE("gpu/single_dense", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_dense", true);
}
TEST_CASE("gpu/conv_batchnorm", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_batchnorm", true);
}
TEST_CASE("gpu/concat_e2e", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "concat_e2e", true);
}
TEST_CASE("gpu/poly_n_8192", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "poly_n_8192", true);
}
TEST_CASE("gpu/conv_act", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_act", true);
}
TEST_CASE("gpu/resnet_basic_block", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "resnet_basic_block", true);
}
TEST_CASE("gpu/poly_n_32768", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "poly_n_32768", true);
}
TEST_CASE("gpu/act_series", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "act_series", true);
}
TEST_CASE("gpu/conv_mch_s1", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_mch_s1", true);
}
TEST_CASE("gpu/conv_mch_s2", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_mch_s2", true);
}
TEST_CASE("gpu/depthwise_conv_s1", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "depthwise_conv_s1", true);
}
TEST_CASE("gpu/depthwise_conv_s2", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "depthwise_conv_s2", true);
}
TEST_CASE("gpu/mux_conv_large_channel", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "mux_conv_large_channel", true);
}
TEST_CASE("gpu/single_avgpool", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_avgpool", true);
}
TEST_CASE("gpu/conv_reshape_dense", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_reshape_dense", true);
}
TEST_CASE("gpu/two_fc", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "two_fc", true);
}
TEST_CASE("gpu/conv1d_e2e", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv1d_e2e", true);
}
TEST_CASE("gpu/conv_avgpool_reshape_dense", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_avgpool_reshape_dense", true);
}
TEST_CASE("gpu/avgpool_stride4", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "avgpool_stride4", true);
}
TEST_CASE("gpu/general_avgpool", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "general_avgpool", true);
}
TEST_CASE("gpu/single_avgpool_big_size", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_avgpool_big_size", true);
}
TEST_CASE("gpu/single_conv_with_stride_big_size", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_conv_with_stride_big_size", true);
}
TEST_CASE("gpu/conv_upsample_e2e", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_upsample_e2e", true);
}
TEST_CASE("gpu/multiple_inputs", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "multiple_inputs", true);
}

TEST_CASE("gpu/multiple_outputs", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "multiple_outputs", true);
}

TEST_CASE("gpu/single_add", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "single_add", true);
}
TEST_CASE("gpu/conv_concat_conv", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "conv_concat_conv", true);
}
TEST_CASE("gpu/dw_conv_big_size", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "dw_conv_big_size", true);
}
TEST_CASE("gpu/uneven_concat", "[e2e][gpu]") {
    run_e2e_test(e2e_base_path / "uneven_concat", true);
}
#endif

// == Known broken tests (disabled) ============================================
// These tests crash (GPU OOM, Go panic, C++ abort) and are disabled until fixed.
// See docs/e2e_test_status.md for details.
//
// Both CPU and GPU:
//   single_add, poly_n_65536_no_btp,
//   btp, conv_series, intertwined
