/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Single-layer E2E inference tests.
//
// Test data is generated by running test_compiler.py::TestE2ESingleLayer which
// produces complete task directories under build/inference/hetero_e2e/single_layer/.
//
// The test list is loaded from ut_names.json (written by the Python test
// after each successful _export_compile_and_deploy call). This avoids stale
// directories left over from deleted Python tests being picked up.
//
// Usage:
//   ./test_e2e_single_layer "[e2e]"                    # Run all tests
//   ./test_e2e_single_layer "[cpu]"                    # Run all CPU tests
//   ./test_e2e_single_layer "[gpu]"                    # Run all GPU tests
//   ./test_e2e_single_layer "cpu/all" -c "conv"        # Run a specific CPU test
//   ./test_e2e_single_layer "cpu/all" -c "conv2d_*"    # Run tests matching pattern

#define CATCH_CONFIG_MAIN
#include "e2e_test_util.h"

static const fs::path single_layer_base_path = e2e_base_path / "single_layer";

// Read test names from ut_names.json written by the Python test suite.
// Falls back to empty list if the manifest does not exist.
static std::vector<std::string> load_test_names(const fs::path& base) {
    std::vector<std::string> names;
    fs::path manifest = base / "ut_names.json";
    if (!fs::exists(manifest))
        return names;
    auto j = read_json(manifest.string());
    for (const auto& entry : j) {
        names.push_back(entry.get<std::string>());
    }
    return names;
}

static const auto single_layer_test_names = load_test_names(single_layer_base_path);

// == Run all (batch) ==========================================================

TEST_CASE("cpu/all", "[batch][cpu][e2e]") {
    REQUIRE_FALSE(single_layer_test_names.empty());
    for (const auto& name : single_layer_test_names) {
        SECTION(name) {
            run_e2e_test(single_layer_base_path / name, false);
        }
    }
}

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/all", "[batch][gpu][e2e]") {
    REQUIRE_FALSE(single_layer_test_names.empty());
    for (const auto& name : single_layer_test_names) {
        SECTION(name) {
            run_e2e_test(single_layer_base_path / name, true);
        }
    }
}
#endif
