/*
 * Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Single-layer E2E inference tests.
//
// Test data is generated by running test_compiler.py::TestE2ESingleLayer which
// produces complete task directories under build/inference/hetero_e2e/<test_name>/.
//
// Usage:
//   ./test_e2e_single_layer "[e2e]"                    # Run all tests
//   ./test_e2e_single_layer "[cpu]"                    # Run all CPU tests
//   ./test_e2e_single_layer "[gpu]"                    # Run all GPU tests
//   ./test_e2e_single_layer "cpu/conv"                 # Run a specific CPU test
//   ./test_e2e_single_layer "gpu/conv"                 # Run a specific GPU test
//   ./test_e2e_single_layer "cpu/all"                  # Run all CPU tests (batch)
//   ./test_e2e_single_layer "gpu/all"                  # Run all GPU tests (batch)

#define CATCH_CONFIG_MAIN
#include "e2e_test_util.h"

static const fs::path single_layer_base_path = e2e_base_path / "single_layer";

// clang-format off
static const std::vector<std::string> single_layer_test_names = {
    // Conv2d (non-depthwise)
    "conv", "conv_mch_s1", "conv_mch_s2", "conv_with_stride_big_size",
    // Conv2d (depthwise)
    "depthwise_conv_s1", "depthwise_conv_s2", "dw_conv_big_size",
    // Conv1d
    "conv1d", "dw_conv1d",
    // FC
    "dense",
    // Pooling
    "avgpool", "avgpool1d", "avgpool_big_size",
    "avgpool_stride4", "general_avgpool",
    // Add
    "add",
    // Activation
    "act",
};
// clang-format on

// == Run all (batch) ==========================================================

TEST_CASE("cpu/all", "[batch][cpu]") {
    for (const auto& name : single_layer_test_names) {
        SECTION(name) {
            run_e2e_test(single_layer_base_path / name, false);
        }
    }
}

#ifdef INFERENCE_SDK_ENABLE_GPU
TEST_CASE("gpu/all", "[batch][gpu]") {
    for (const auto& name : single_layer_test_names) {
        SECTION(name) {
            run_e2e_test(single_layer_base_path / name, true);
        }
    }
}
#endif

// == CPU tests ================================================================

// Conv2d (non-depthwise)
TEST_CASE("cpu/conv", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "conv", false);
}
TEST_CASE("cpu/conv_mch_s1", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "conv_mch_s1", false);
}
TEST_CASE("cpu/conv_mch_s2", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "conv_mch_s2", false);
}
TEST_CASE("cpu/conv_with_stride_big_size", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "conv_with_stride_big_size", false);
}

// Conv2d (depthwise)
TEST_CASE("cpu/depthwise_conv_s1", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "depthwise_conv_s1", false);
}
TEST_CASE("cpu/depthwise_conv_s2", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "depthwise_conv_s2", false);
}
TEST_CASE("cpu/dw_conv_big_size", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "dw_conv_big_size", false);
}

// Conv1d
TEST_CASE("cpu/conv1d", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "conv1d", false);
}
TEST_CASE("cpu/dw_conv1d", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "dw_conv1d", false);
}

// FC
TEST_CASE("cpu/dense", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "dense", false);
}

// Pooling
TEST_CASE("cpu/avgpool", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "avgpool", false);
}
TEST_CASE("cpu/avgpool1d", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "avgpool1d", false);
}
TEST_CASE("cpu/avgpool_big_size", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "avgpool_big_size", false);
}
TEST_CASE("cpu/avgpool_stride4", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "avgpool_stride4", false);
}
TEST_CASE("cpu/general_avgpool", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "general_avgpool", false);
}

// Add
TEST_CASE("cpu/add", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "add", false);
}

// Activation
TEST_CASE("cpu/act", "[e2e][cpu]") {
    run_e2e_test(single_layer_base_path / "act", false);
}

// == GPU tests ================================================================

#ifdef INFERENCE_SDK_ENABLE_GPU

// Conv2d (non-depthwise)
TEST_CASE("gpu/conv", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "conv", true);
}
TEST_CASE("gpu/conv_mch_s1", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "conv_mch_s1", true);
}
TEST_CASE("gpu/conv_mch_s2", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "conv_mch_s2", true);
}
TEST_CASE("gpu/conv_with_stride_big_size", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "conv_with_stride_big_size", true);
}

// Conv2d (depthwise)
TEST_CASE("gpu/depthwise_conv_s1", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "depthwise_conv_s1", true);
}
TEST_CASE("gpu/depthwise_conv_s2", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "depthwise_conv_s2", true);
}
TEST_CASE("gpu/dw_conv_big_size", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "dw_conv_big_size", true);
}

// Conv1d
TEST_CASE("gpu/conv1d", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "conv1d", true);
}
TEST_CASE("gpu/dw_conv1d", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "dw_conv1d", true);
}

// FC
TEST_CASE("gpu/dense", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "dense", true);
}

// Pooling
TEST_CASE("gpu/avgpool", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "avgpool", true);
}
TEST_CASE("gpu/avgpool1d", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "avgpool1d", true);
}
TEST_CASE("gpu/avgpool_big_size", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "avgpool_big_size", true);
}
TEST_CASE("gpu/avgpool_stride4", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "avgpool_stride4", true);
}
TEST_CASE("gpu/general_avgpool", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "general_avgpool", true);
}

// Add
TEST_CASE("gpu/add", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "add", true);
}

// Activation
TEST_CASE("gpu/act", "[e2e][gpu]") {
    run_e2e_test(single_layer_base_path / "act", true);
}

#endif
